on:
  push:
    branches:
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
  print_nombre:
    runs-on: ubuntu-latest
    steps:
      - run: echo "David"
      - run: echo "Cierre"
