# Nombre del workflow
name: Only Pytests & sonarqube

on:
  push:
    branches:
      - main
      - dev

jobs:
  various_integrated_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setting JDK 17...
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Python config.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Pytest
        run: pip install pytest

      - name: Run pytests
        run: | 
          echo $(pytest -s -v --disable-pytest-warnings unit_tests\pytest) > results.txt
          cat results.txt

      - name: Install Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "PATH=$PATH:$(pwd)/sonar-scanner/bin" >> $GITHUB_ENV

      - name: Verify SonarQube...
        run: |
          sudo curl -I http://rnatu-77-231-9-10.a.free.pinggy.link
        continue-on-error: true

      - name: Check code in SonarQube...
        env:
          SONAR_TOKEN: ${{ secrets.MAIN_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.python.version=3.x \
            -Dsonar.projectKey=VariosTests \
            -Dsonar.host.url=http://rnatu-77-231-9-10.a.free.pinggy.link \
            -Dsonar.token=$MAIN_TOKEN \
            -Dsonar.sources=src/com/example/sqlinjectiontest/Main.java \
            -Dsonar.sources=python/file.py \
            -Dsonar.qualitygate.wait=true \
            -X